# LVGL Odin Bindings Generator
# Takes bindings.nix and produces Odin foreign import code
{ pkgs ? import <nixpkgs> {} }:
let
  bindings = import ./bindings.nix;
  lib = pkgs.lib;

  # Generate opaque struct declarations
  genOpaqueTypes = types:
    lib.concatMapStringsSep "\n" (t: "${t} :: struct {}") types;

  # Generate enum with explicit values
  genEnum = name: values:
    let
      # Generate each value with index
      genValue = idx: val: "    ${val} = ${toString idx},";
      indexed = lib.imap0 genValue values;
    in ''
${name} :: enum i32 {
${lib.concatStringsSep "\n" indexed}
}'';

  # Generate all enums
  genEnums = enums:
    lib.concatStringsSep "\n\n" (lib.mapAttrsToList genEnum enums);

  # Generate type aliases
  genAliases = aliases:
    lib.concatStringsSep "\n" (lib.mapAttrsToList (name: type:
      "${name} :: ${type};"
    ) aliases);

  # Generate function argument
  genArg = arg: "${arg.name}: ${arg.type}";

  # Generate function arguments list
  genArgs = args:
    if args == [] then ""
    else lib.concatMapStringsSep ", " genArg args;

  # Generate return type
  genRet = ret:
    if ret == "void" then ""
    else " -> ${ret}";

  # Generate a single foreign function
  genFunction = name: spec:
    "    ${name} :: proc(${genArgs spec.args})${genRet spec.ret} ---";

  # Generate all foreign functions
  genFunctions = funcs:
    lib.concatStringsSep "\n" (lib.mapAttrsToList genFunction funcs);

  # Full Odin source
  odinSource = ''
// LVGL Odin Bindings
// Auto-generated by LVGL-Nix/binder.nix
// Do not edit manually

package lvgl

foreign import lvgl_lib "liblvgl.a"

// === Opaque Types ===
${genOpaqueTypes bindings.opaqueTypes}

// === Enums ===
${genEnums bindings.enums}

// === Type Aliases ===
${genAliases bindings.aliases}

// === Foreign Functions ===
@(default_calling_convention = "c")
foreign lvgl_lib {
${genFunctions bindings.functions}
}

// === Helper Constants ===
LV_SIZE_CONTENT :: -1
LV_PCT :: proc(x: i32) -> i32 { return 2000 + x }  // Percentage size
LV_OPA_TRANSP :: 0
LV_OPA_COVER :: 255
'';

in pkgs.writeText "lvgl.odin" odinSource
